aventon/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * !! ACÁ SE PUEDE MODIFICAR TODAS LAS RUTAS - IMPORTANTE !!
 * Verbos en el protocolo HTTP: get, post, put.
 */

Route::get('/', function () {
    $travels = App\Travel::orderBy('departure_date','ASC')->where('multiple_id', '=', NULL)->where('arrival_date', '>=', date('Y-m-d H:i:s'))->paginate(7);
    return view('welcome', compact('travels'));
});

// AUTH

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')
        ->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')
        ->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')
        ->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')
        ->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')
        ->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')
        ->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/**
 * Rutas (cars, users, travels, questions, ratings) (Antes de los resources).
 */

// USERS
Route::pattern('users', '[0-9]+');
Route::get('/users/{user}/password', 'UserController@editPassword')
        ->name('users.edit_password');
Route::match(['put', 'patch'], '/users/{user}/password', 'UserController@updatePassword')
        ->name('users.update_password');
Route::get('/users/{user}/destroy', 'UserController@validateDestroy')
        ->name('users.validate_destroy');


// CARS
Route::pattern('cars', '[0-9]+');


// TRAVELS
Route::pattern('travels', '[0-9]+');
Route::get('/travels/{travel}/destroy', 'TravelController@validateDestroy')
        ->name('travels.validate_destroy');
Route::get('/travels/{travel}/selections', 'TravelController@showSelections')
        ->name('travels.show_selections');
Route::get('/travels/{travel}/passenger/{user}', 'TravelController@showPassenger')
        ->name('travels.show_passenger');
Route::get('/travels/search', 'TravelController@searchTravel')
    ->name('travels.search_travel');
Route::get('/travels/create_multiple', 'TravelController@createMultiple')
    ->name('travels.create_multiple');
Route::get('/travels/{travel}/edit_multiple', 'TravelController@editMultiple')
    ->name('travels.edit_multiple');
Route::match(['put', 'patch'], '/travels/{travel}/update_multiple', 'TravelController@updateMultiple')
    ->name('travels.update_multiple');
Route::post('/travels/store_multiple', 'TravelController@storeMultiple')
    ->name('travels.store_multiple');

// TRAVELS - POSTULANT
Route::get('/travels/{travel}/exit/{user}', 'TravelController@exitTravel')
        ->name('travels.exit_postulant');
Route::get('/travels/{travel}/exit_penal/{user}', 'TravelController@exitTravelWithPenal')
        ->name('travels.exit_postulant_penal');
Route::get('/travels/{travel}/delete/{user}', 'TravelController@deletePassenger')
        ->name('travels.delete_passenger');
Route::get('/travels/{travel}/postulants', 'TravelController@showPostulants')
        ->name('travels.show_postulants');
Route::get('/travels/{travel}/postulate', 'TravelController@postulate')
        ->name('travels.postulate');
Route::get('/travels/{travel}/reject/{user}', 'TravelController@rejectPostulant')
        ->name('travels.reject_postulant');
Route::get('/travels/{travel}/accept/{user}', 'TravelController@acceptPostulant')
        ->name('travels.accept_postulant');


// QUESTIONS
Route::pattern('questions', '[0-9]+');


// RATINGS
Route::pattern('ratings', '[0-9]+');
Route::get('/ratings/rate/{user}', 'RatingController@showRatings')
    ->name('ratings.show_ratings');


/**
 * Se genera CRUD's (index, store, create, destroy, update, show, edit).
 */

Route::resource('users','UserController');
Route::resource('cars','CarController');
Route::resource('travels','TravelController');
Route::resource('questions','QuestionController');
Route::resource('ratings','RatingController');

// HOME
Route::get('/home', 'HomeController@index')->name('home');

//CONTACTO
Route::get('/contact', 'ContactoController@contact')
        ->name('contact');

//AYUDA
Route::get('/ayuda', 'AyudaController@ayuda')
        ->name('ayuda');

aventon/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use App\Notifications\ResetPasswordNotification;
use Illuminate\Foundation\Auth\User as Authenticatable;



class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','lastname','email','password','birthdate',
        'driver_qualification','passenger_qualification',
        'account','owedpenalized','owedqualification','low'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];

    public function cars()
    {
        return $this->belongsToMany(Car::class)->withTimestamps();
    }

    public function travels()
    {
        return $this->belongsToMany(Travel::class)->withTimestamps();
    }

    public function ratings()
    {
        return $this->hasMany(Rating::class);
    }

    public function selection()
    {
        return $this->hasOne(Rating::class);
    }

    public function questions()
    {
      return $this->hasMany(Question::class);
    }

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        //$this->notify(new ResetPasswordNotification($token));
        return back()
            ->with('info', 'La respuesta fue enviada.');
    }
}

aventon/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Providers\AuthServiceProvider;
use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Auth;

// APPS AVENTON
use App\User;
use App\Car;
use App\Travel;
use App\Selection;
use App\Rating;

class UserController extends Controller
{
  /*
   * Funciones por defecto generadas por Route::resource en routes/web.php:
   * (index, store, create, destroy, update, show, edit).
   */

  public function index()
  {
    //
  }

  /*
   * Ni store, ni create se utilizan.
   * RegisterController hace estas funciones.
   */

  public function store(UserRequest $request)
  {
    //
  }


  public function create()
  {
    //
  }


  // Primero se ejecuta validateDestroy.
  public function destroy($id)
  {
    $user = User::find($id);
    $travels = Travel::where('user_id', '=', $user->id)->get();
    $cars = $user->cars()->where('user_id', '=', $user->id)->get();

    foreach( $travels as $travel )
    {
      $this->destroyTravel($travel->id);
    }

    foreach( $cars as $car )
    {
      $this->destroyCar($car->id);
    }

    User::where('id',$user->id)->delete();

    return redirect('/')
            ->with('info', 'El usuario fue eliminado.');
  }


  public function update(UserRequest $request, $id)
  {
    $user = Auth::User();

    if( $user->id == $id )
    {
      $user->name       = $request->name;
      $user->lastname   = $request->lastname;
      $user->birthdate  = $request->birthdate;

      $user->save();

      return redirect()
              ->route('users.show', $user)
              ->with('info', 'El usuario '.$user->name.' fue actualizado.');
    }
    else
    {
      return redirect('/')
              ->with('info', 'Acceso denegado.');
    }
  }


  public function show($id)
  {
    $user = Auth::User();

    if( $user->id == $id )
    {
      $drive_travels = Travel::where('user_id', '=', $id)->where('multiple_id', '=', NULL)->where('arrival_date', '>=', date('Y-m-d H:i:s'))->get();

      $postulant_travels = $user->travels()->where('multiple_id', '=', NULL)->where('arrival_date', '>', date('Y-m-d H:i:s'))->get();

      $selection_travels = array();
      $selections = Selection::where('user_id', $user->id)->get();

      foreach( $selections as $selection )
      {
        $travel = Travel::find($selection->travel_id);

        if(!$travel->multiple)
        {
          $selection_travels = array_add($selection_travels, $travel->id, $travel);
        }

        if( ($travel->multiple_id == NULL) and ($travel->multiple) )
        {
          $sub_travels = Travel::where('multiple_id', '=', $travel->id)->get();
          $max_date_travel = $sub_travels->max('arrival_date');

          if( $max_date_travel > date('Y-m-d H:i:s') )
          {
            $selection_travels = array_add($selection_travels, $travel->id, $travel);
          }
        }
      }

      return view('users.show', compact('user', 'drive_travels', 'postulant_travels', 'selection_travels'));
    }
    else
    {
      return redirect('/')
              ->with('info', 'Acceso denegado.');
    }
  }


  public function edit($id)
  {
    $user = Auth::User();

    if( $user->id == $id )
    {
      $user = User::find($id);
      return view('users.edit', compact('user'));
    }
    else
    {
      return redirect('/')
              ->with('info', 'Acceso denegado.');
    }
  }

  /*
   * Demás funciones...
   */

  public function validateDestroy($id)
  {
      $user = Auth::User();
      if( $user->id == $id )
      {
          $hasRatings = $user->ratings()->where('date_for_rating', '<', date('Y-m-d H:i:s'))->exists();
          if( $hasRatings )
          {
              return back()
                  ->with('info', 'No puedes borrar tu cuenta, porque debes calificaciones.');
          }
          else
          {
              $travels = $user->travels()->get();
              foreach ($travels as $travel)
              {

                  if($travel->arrival_date > date('Y-m-d H:i:s'))
                  {
                    
                    $hasPassangers = Selection::where('travel_id', $travel->id)->exists();
                    if ( $hasPassangers )
                    {
                         return back()
                              ->with('info', 'No puedes borrar tu cuenta, porque tienes pasajeros en algún viaje.');
                    }

                  }
              }
          }
          return view('users.validate_destroy', compact('user'));
      }
      else
      {
          return redirect('/')
              ->with('info', 'Acceso denegado.');
      }
  }



  public function editPassword($id)
  {
    $user = Auth::User();

    if( $user->id == $id )
    {
      return view('users.edit_password', compact('user'));
    }
    else
    {
      return redirect('/')
              ->with('info', 'Acceso denegado.');
    }
  }


  public function updatePassword(UserRequest $request, $id)
  {
    $user = Auth::User();

    if( $user->id == $id )
    {
      $user->password = bcrypt($request->password);

      $user->save();

      return redirect()
              ->route('users.show', $user)
              ->with('info', 'La contraseña fue actualizada.');
    }
    else
    {
      return redirect('/')
              ->with('info', 'Acceso denegado.');
    }
  }


  public function destroyTravel($id)
    {
        $travel = Travel::find($id);
        $user   = Auth::user();

        // Elimina pasajeros y penaliza +1 por cada uno.
        if ( $travel->selections->count() != 0 )
        {
            foreach ($travel->selections as $selection )
            {
                $selection->delete();
                $user->decrement('driver_qualification');
            }
        }

        // Quita relación viaje-postulantes y penaliza +1.
        if ( $travel->users->count() > 1 )
        {
            foreach ($travel->users as $postulant )
            {
                $postulant->travels()->detach($travel->id);
            }

            $user->decrement('driver_qualification');
        }

        // Quita relación usuario-viaje.
        $user->travels()->detach($travel->id);

        // Elimina preguntas y respuestas.
        if ( $travel->questions->count() != 0 )
        {
            foreach ($travel->questions as $question )
            {
                $question->delete();
            }
        }

        // Elimina calificaciones teniendo encuenta ambos campos de user.
        if ( $travel->ratings->count() != 0 )
        {
            foreach ( Rating::all() as $rating )
            {
                if ( $rating->user_to_rating = $user->id or $rating->user_id = $user->id )
                {
                    $rating->delete();
                }
            }
        }

        $travel->delete();
    }

    public function destroyCar($id)
    {
        $car = Car::find($id);
        $car->users()->detach(Auth::user()->id);
        $car->delete();
    }

}

aventon/resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
  @include('layouts.alerts')

  <div class="card col-md-5 mx-auto">
    <div class="card-header">
      <h5>
        {{ __('Correo electronico: ').Auth::user()->email }}

        <a class="btn btn-primary float-right" role="button" href="{{ route('users.show', Auth::user()) }}">
          {{ __('Volver') }}
        </a>
      </h5>
    </div>

    <div class="card-body">
      {!! Form::model(Auth::user(), ['route' => ['users.update', Auth::user()], 'method' => 'PUT']) !!}

        @include('users.fragment.form')

      {!! Form::close() !!}

      <div class="form-group">
        <a class="btn btn-primary float-left" role="button" href="{{ route('users.edit_password', Auth::user()) }}">
          <img src="{{ asset('iconic-svg/pencil.svg') }}" alt="{{ __('Cambiar Contraseña') }}">  {{ __('Cambiar Contraseña') }}
        </a>
      </div>

      <div class="form-group">
        <a class="btn btn-primary float-right" role="button" href="{{ route('users.validate_destroy', Auth::user()) }}">
          <img src="{{ asset('iconic-svg/trash.svg') }}" alt="{{ __('Eliminar Usuario') }}">  {{ __('Eliminar Usuario') }}
        </a>
      </div>
    </div>
  </div>
@endsection

aventon/resources/views/users/edit_password.blade.php
@extends('layouts.app')

@section('content')
  @include('layouts.alerts')

  <div class="card col-md-5 mx-auto">
    <div class="card-header">
      <h5>
        {{ Auth::user()->name }}

        <a class="btn btn-primary float-right" role="button" href="{{ route('users.edit', Auth::user()) }}">
          Volver
        </a>
      </h5>
    </div>

    <div class="card-body">
      {!! Form::model($user, ['route' => ['users.update_password', Auth::user()], 'method' => 'PUT']) !!}

        <h3>
          {{ __('Nueva contraseña:') }}
        </h3>

        <div class="form-group row">
            <label for="password" class="col-md-4 col-form-label text-md-right">
                {{ __('Contraseña') }}
            </label>

            <div class="col-md-6">
                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">
                {{ __('Confirmar Contraseña') }}
            </label>

            <div class="col-md-6">
                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    <img src="{{ asset('iconic-svg/pencil.svg') }}" alt="{{ __('Modificar') }}">  {{ __('Modificar') }}
                </button>
            </div>
        </div>

      {!! Form::close() !!}
    </div>
  </div>
@endsection

aventon/resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
  @include('layouts.alerts')

  <div class="row margenes-cajas">
    <div class="box-index card col-md-5 mx-auto">
      <div class="card-header">
        <h5>
          {{ __('Mi usuario') }}

          <a class="btn btn-primary float-right" role="button" href="{{ route('users.edit', Auth::user()) }}">
            <img src="{{ asset('iconic-svg/pencil.svg') }}" alt="{{ __('Editar') }}">  {{ __('Editar') }}
          </a>
        </h5>
      </div>
      <div class="card-body">
        @include('layouts.show_user')
      </div>
    </div>

    <div class="box-index card col-md-4 mx-auto">
      <div class="card-header">
        <h5>
          {{ __('Mis autos') }}

          <a class="btn btn-primary float-right" role="button" href="{{ route('cars.create') }}">
            <img src="{{ asset('iconic-svg/plus.svg') }}" alt="{{ __('Nuevo auto') }}">  {{ __('Nuevo auto') }}
          </a>
        </h5>
      </div>
      <div class="card-body">
        @include('layouts.list_cars_user')
      </div>
    </div>
  </div>

  <div class="row margenes-cajas">
    <div class="box-index card col-md-10 mx-auto">
      <div class="card-header">
        <h5>
          {{ __('Mis viajes como conductor:  ') }}
          <button class="btn btn-primary dropdown-toggle float-right" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ __('Crear viaje') }} <span class="caret"></span>
          </button>

          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

            <a class="dropdown-item" href="{{ route('travels.create') }}">
              <img src="{{ asset('iconic-svg/plus.svg') }}" alt="{{ __('Simple') }}">  {{ __('Simple') }}
            </a>
            <a class="dropdown-item" href="{{ route('travels.create_multiple') }}">
              <img src="{{ asset('iconic-svg/plus.svg') }}" alt="{{ __('Multiple') }}">  {{ __('Multiple') }}
            </a>
          </div>
        </h5>
      </div>
      <div class="card-body">
        @include('layouts.list_travels_driver')
      </div>
    </div>
  </div>

  <div class="row margenes-cajas">
    <div class="box-index card col-md-10 mx-auto">
      <div class="card-header">
        <h5>
          {{ __('Mis viajes como pasajero: ') }}
        </h5>
      </div>
      <div class="card-body">
        @include('layouts.list_travels_selection')
      </div>
    </div>
  </div>

  <div class="row margenes-cajas">
    <div class="box-index card col-md-10 mx-auto">
      <div class="card-header">
        <h5>
          {{ __('Mis viajes como postulante: ') }}
        </h5>
      </div>
      <div class="card-body">
        @include('layouts.list_travels_postulant')
      </div>
    </div>
  </div>
@endsection

aventon/resources/views/users/validate_destroy.blade.php
@extends('layouts.app')

@section('content')
  @include('layouts.alerts')

  <div class="card col-md-5 mx-auto">
    <div class="card-header">
      <h5>
        {{ Auth::user()->name }}

        <a class="btn btn-primary float-right" role="button" href="{{ route('users.show', Auth::user()) }}">
          Volver
        </a>
      </h5>
    </div>

    <div class="card-body">
      <h4>
        {{ __('¿Quieres eliminar tu cuenta?.') }}
      </h4>

      <div class="form-group">
        <form action="{{ route('users.destroy', Auth::user()) }}" method="post">
          {{ csrf_field() }}
          <input type="hidden" name="_method" value="DELETE">
          <button class="btn btn-primary float-right">
            <img src="{{ asset('iconic-svg/warning.svg') }}" alt="{{ __('Eliminar Cuenta') }}">  {{ __('Eliminar Cuenta') }}
          </button>
        </form>
      </div>
    </div>
  </div>
@endsection