aventon/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * !! ACÁ SE PUEDE MODIFICAR TODAS LAS RUTAS - IMPORTANTE !!
 * Verbos en el protocolo HTTP: get, post, put.
 */

Route::get('/', function () {
    $travels = App\Travel::orderBy('departure_date','ASC')->where('multiple_id', '=', NULL)->where('arrival_date', '>=', date('Y-m-d H:i:s'))->paginate(7);
    return view('welcome', compact('travels'));
});

// AUTH

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')
        ->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')
        ->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')
        ->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')
        ->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')
        ->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')
        ->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/**
 * Rutas (cars, users, travels, questions, ratings) (Antes de los resources).
 */

// USERS
Route::pattern('users', '[0-9]+');
Route::get('/users/{user}/password', 'UserController@editPassword')
        ->name('users.edit_password');
Route::match(['put', 'patch'], '/users/{user}/password', 'UserController@updatePassword')
        ->name('users.update_password');
Route::get('/users/{user}/destroy', 'UserController@validateDestroy')
        ->name('users.validate_destroy');


// CARS
Route::pattern('cars', '[0-9]+');


// TRAVELS
Route::pattern('travels', '[0-9]+');
Route::get('/travels/{travel}/destroy', 'TravelController@validateDestroy')
        ->name('travels.validate_destroy');
Route::get('/travels/{travel}/selections', 'TravelController@showSelections')
        ->name('travels.show_selections');
Route::get('/travels/{travel}/passenger/{user}', 'TravelController@showPassenger')
        ->name('travels.show_passenger');
Route::get('/travels/search', 'TravelController@searchTravel')
    ->name('travels.search_travel');
Route::get('/travels/create_multiple', 'TravelController@createMultiple')
    ->name('travels.create_multiple');
Route::get('/travels/{travel}/edit_multiple', 'TravelController@editMultiple')
    ->name('travels.edit_multiple');
Route::match(['put', 'patch'], '/travels/{travel}/update_multiple', 'TravelController@updateMultiple')
    ->name('travels.update_multiple');
Route::post('/travels/store_multiple', 'TravelController@storeMultiple')
    ->name('travels.store_multiple');

// TRAVELS - POSTULANT
Route::get('/travels/{travel}/exit/{user}', 'TravelController@exitTravel')
        ->name('travels.exit_postulant');
Route::get('/travels/{travel}/exit_penal/{user}', 'TravelController@exitTravelWithPenal')
        ->name('travels.exit_postulant_penal');
Route::get('/travels/{travel}/delete/{user}', 'TravelController@deletePassenger')
        ->name('travels.delete_passenger');
Route::get('/travels/{travel}/postulants', 'TravelController@showPostulants')
        ->name('travels.show_postulants');
Route::get('/travels/{travel}/postulate', 'TravelController@postulate')
        ->name('travels.postulate');
Route::get('/travels/{travel}/reject/{user}', 'TravelController@rejectPostulant')
        ->name('travels.reject_postulant');
Route::get('/travels/{travel}/accept/{user}', 'TravelController@acceptPostulant')
        ->name('travels.accept_postulant');


// QUESTIONS
Route::pattern('questions', '[0-9]+');


// RATINGS
Route::pattern('ratings', '[0-9]+');
Route::get('/ratings/rate/{user}', 'RatingController@showRatings')
    ->name('ratings.show_ratings');


/**
 * Se genera CRUD's (index, store, create, destroy, update, show, edit).
 */

Route::resource('users','UserController');
Route::resource('cars','CarController');
Route::resource('travels','TravelController');
Route::resource('questions','QuestionController');
Route::resource('ratings','RatingController');

// HOME
Route::get('/home', 'HomeController@index')->name('home');

//CONTACTO
Route::get('/contact', 'ContactoController@contact')
        ->name('contact');

//AYUDA
Route::get('/ayuda', 'AyudaController@ayuda')
        ->name('ayuda');

aventon/resources/views/layouts/list_cars_user.blade.php
<div class="table-responsive">
  <table class="table table-hover">
    <tbody>
      @foreach(Auth::user()->cars as $car)
      <tr>
        <td>
          <strong>
            {{ $car->patent }}
          </strong>
        </td>
        <td>
          <a href="{{ route('cars.show', $car) }}" class="btn btn-primary">
            <img src="{{ asset('iconic-svg/eye.svg') }}" alt="{{ __('Ver') }}">  {{ __('Ver') }}
          </a>
        </td>
        <td>
          <a href="{{ route('cars.edit', $car) }}" class="btn btn-primary">
            <img src="{{ asset('iconic-svg/pencil.svg') }}" alt="{{ __('Editar') }}"> {{ __('Editar') }}
          </a>
        </td>
        <td>
          <form action="{{ route('cars.destroy', $car) }}" method="post">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="DELETE">
            <button class="btn btn-primary">
              <img src="{{ asset('iconic-svg/trash.svg') }}" alt="{{ __('Borrar') }}"> {{ __('Borrar') }}
            </button>
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>

aventon/resources/views/layouts/list_ratings.blade.php
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Fecha disponible para calificar</th>
            <th>Usuario a calificar</th>
            <th>Rol</th>
        </tr>
        </thead>
        <tbody>
        @foreach($ratings as $rating)
            @if($rating->rate == false)
            <tr>
                <td>{{ $rating->date_for_rating }}</td>
                <td>{{ $rating->user_to_rating($rating)->name }}</td>
                @if( $rating->user_to_rating == $rating->travel->user_id )
                    <td> Conductor </td>
                @else
                    <td> Pasajero </td>
                @endif
            </tr>
            <tr>
              <td colspan="3">
                {!! Form::model($rating, ['route' => ['ratings.update', $rating], 'method' => 'PUT']) !!}
                  <div class="form-group">
                    {!! Form::label('qualification', 'Calificación:') !!}<br>
                    {!! Form::select('qualification', ['Positive' => 'Positivo', 'Neutral' => 'Neutral', 'Negative' => 'Negativo'], null, ['class' => 'form-control']) !!}
                  </div>
                  <div class="form-group">
                    {!! Form::label('content', 'Comentario:') !!}
                    {!! Form::textarea('content', null , ['class' => 'form-control ','rows'=>'3' ,'cols'=>'50', 'placeholder' => 'Ingrese comentario ', 'required', 'min'=>'5']) !!}
                  </div>
                  <div class="form-group">
                    {!! Form::hidden('rating_id', $rating->id, ['class' => 'form-control', 'readonly']) !!}
                  </div>
                  <div class="form-group">
                    {!! Form::submit('Calificar', ['class' => 'btn btn-primary']) !!}
                  </div>
                {!! Form::close() !!}
              </td>
            </tr>
            @endif
        @endforeach
        </tbody>
    </table>
    {!! $ratings->render() !!}
</div>

aventon/resources/views/layouts/list_travels.blade.php
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Fecha Salida</th>
        <th>Hora Salida</th>
        <th>Costo</th>
        <th>Localidad de Salida</th>
        <th>Localidad de Llegada</th>
        <th>Plazas Vacias</th>
        <th>Fecha Llegada</th>
        <th>Hora Llegada</th>
        <th>Origen Provincia</th>
        <th>Destino Provincia</th>
        <th>Dirección Salida</th>
        <th>Dirección Llegada</th>
      </tr>
    </thead>
    <tbody>
      @foreach($travels as $travel)
        <tr>
          <td>{{ $travel->departure_date }}</td>
          <td>{{ $travel->departure_time }}</td>
          <td>{{ $travel->cost }}</td>
          <td>{{ $travel->source_locality }}</td>
          <td>{{ $travel->destiny_locality }}</td>
          <td>{{ $travel->car->places }}</td>
          <td>{{ $travel->arrival_date }}</td>
          <td>{{ $travel->arrival_time }}</td>
          <td>{{ $travel->source_province }}</td>
          <td>{{ $travel->destiny_province }}</td>
          <td>{{ $travel->departure_address }}</td>
          <td>{{ $travel->arrival_address }}</td>
        </tr>
      @endforeach
    </tbody>
  </table>

  {!! $travels->render() !!}
</div>

aventon/resources/views/layouts/list_travels_driver.blade.php
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Fecha Salida</th>
        <th>Hora Salida</th>
        <th>Costo</th>
        <th>Localidad de Salida</th>
        <th>Localidad de Llegada</th>
        <th>Plazas Vacias</th>
      </tr>
    </thead>
    <tbody>
      @foreach( $drive_travels as $travel )
        <tr>
          <td>{{ $travel->departure_date }}</td>
          <td>{{ $travel->departure_time }}</td>
          <td>{{ $travel->cost }}</td>
          <td>{{ $travel->source_locality }}</td>
          <td>{{ $travel->destiny_locality }}</td>
          <td>{{ $travel->car->places }}</td>
          
          @if( $travel->multiple )
            <td>
              <a href="{{ route('travels.show', $travel) }}" class="btn btn-primary">
                <img src="{{ asset('iconic-svg/eye.svg') }}" alt="{{ __('Ver Multiple') }}">  {{ __('Ver Multiple') }}
              </a>
            </td>
            <td>
              <a href="{{ route('travels.edit_multiple', $travel) }}" class="btn btn-primary">
                <img src="{{ asset('iconic-svg/pencil.svg') }}" alt="{{ __('Editar') }}">  {{ __('Editar Multiple') }}
              </a>
            </td>
          @else
            <td>
              <a href="{{ route('travels.show', $travel) }}" class="btn btn-primary">
                  <img src="{{ asset('iconic-svg/eye.svg') }}" alt="{{ __('Ver') }}">  {{ __('Ver') }}
              </a>
            </td>
            <td>
              <a href="{{ route('travels.edit', $travel) }}" class="btn btn-primary">
                <img src="{{ asset('iconic-svg/pencil.svg') }}" alt="{{ __('Editar') }}">  {{ __('Editar') }}
              </a>
            </td>
          @endif

          <td>
            <a href="{{ route('travels.validate_destroy', $travel) }}" class="btn btn-primary">
              <img src="{{ asset('iconic-svg/trash.svg') }}" alt="{{ __('Borrar') }}">  {{ __('Borrar') }}
            </a>
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>
</div>

aventon/resources/views/layouts/list_travels_home.blade.php
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Fecha Salida</th>
            <th>Hora Salida</th>
            <th>Costo</th>
            <th>Localidad de Salida</th>
            <th>Localidad de Llegada</th>
        </tr>
        </thead>
        <tbody>
        @foreach( $travels as $travel )
            <tr>
                <td>{{ $travel->departure_date }}</td>
                <td>{{ $travel->departure_time }}</td>
                <td>{{ $travel->cost }}</td>
                <td>{{ $travel->source_locality }}</td>
                <td>{{ $travel->destiny_locality }}</td>
                <td>
                    @if( $travel->multiple )
                      <a href="{{ route('travels.show', $travel) }}" class="btn btn-primary">
                          <img src="{{ asset('iconic-svg/eye.svg') }}" alt="{{ __('Ver Multiple') }}">  {{ __('Ver Multiple') }}
                      </a>
                    @else
                      <a href="{{ route('travels.show', $travel) }}" class="btn btn-primary">
                          <img src="{{ asset('iconic-svg/eye.svg') }}" alt="{{ __('Ver') }}">  {{ __('Ver') }}
                      </a>
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {!! $travels->render() !!}
</div>

aventon/resources/views/layouts/list_travels_postulant.blade.php
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Fecha Salida</th>
        <th>Hora Salida</th>
        <th>Costo</th>
        <th>Localidad de Salida</th>
        <th>Localidad de Llegada</th>
        <th>Plazas Vacias</th>
        <th>Fecha Llegada</th>
        <th>Hora Llegada</th>
      </tr>
    </thead>
    <tbody>
      @foreach( $postulant_travels as $travel)
        @if ( $user->id != $travel->user_id )
          <tr>
            <td>{{ $travel->departure_date }}</td>
            <td>{{ $travel->departure_time }}</td>
            <td>{{ $travel->cost }}</td>
            <td>{{ $travel->source_locality }}</td>
            <td>{{ $travel->destiny_locality }}</td>
            <td>{{ $travel->car->places }}</td>
            <td>{{ $travel->arrival_date }}</td>
            <td>{{ $travel->arrival_time }}</td>
            <td>
              @if( $travel->multiple )
                <a href="{{ route('travels.show', $travel) }}" class="btn btn-primary">
                    <img src="{{ asset('iconic-svg/eye.svg') }}" alt="{{ __('Ver Multiple') }}">  {{ __('Ver Multiple') }}
                </a>
              @else
                <a href="{{ route('travels.show', $travel) }}" class="btn btn-primary">
                    <img src="{{ asset('iconic-svg/eye.svg') }}" alt="{{ __('Ver') }}">  {{ __('Ver') }}
                </a>
              @endif
            </td>
            <td>
              <a href="{{ route('travels.exit_postulant', ['travel'=> $travel, 'user' => Auth::User()->id]) }}" class="btn btn-primary">
                <img src="{{ asset('iconic-svg/trash.svg') }}" alt="{{ __('Borrar') }}">  {{ __('Borrar') }}
              </a>
            </td>
          </tr>
        @endif
      @endforeach
    </tbody>
  </table>
</div>

aventon/resources/views/layouts/list_travels_selection.blade.php
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Fecha Salida</th>
        <th>Hora Salida</th>
        <th>Costo</th>
        <th>Localidad de Salida</th>
        <th>Localidad de Llegada</th>
        <th>Plazas Vacias</th>
        <th>Fecha Llegada</th>
        <th>Hora Llegada</th>
      </tr>
    </thead>
    <tbody>
      @foreach( $selection_travels as $travel )
          <tr>
            <td>{{ $travel->departure_date }}</td>
            <td>{{ $travel->departure_time }}</td>
            <td>{{ $travel->cost }}</td>
            <td>{{ $travel->source_locality }}</td>
            <td>{{ $travel->destiny_locality }}</td>
            <td>{{ $travel->car->places }}</td>
            <td>{{ $travel->arrival_date }}</td>
            <td>{{ $travel->arrival_time }}</td>
            <td>
              @if( $travel->multiple )
                <a href="{{ route('travels.show', $travel) }}" class="btn btn-primary">
                    <img src="{{ asset('iconic-svg/eye.svg') }}" alt="{{ __('Ver Multiple') }}">  {{ __('Ver Multiple') }}
                </a>
              @else
                <a href="{{ route('travels.show', $travel) }}" class="btn btn-primary">
                    <img src="{{ asset('iconic-svg/eye.svg') }}" alt="{{ __('Ver') }}">  {{ __('Ver') }}
                </a>
              @endif
            </td>
            <td>
              <a href="{{ route('travels.exit_postulant_penal', ['travel'=> $travel, 'user' => Auth::User()->id]) }}" class="btn btn-primary">
                <img src="{{ asset('iconic-svg/trash.svg') }}" alt="{{ __('Borrar') }}">  {{ __('Borrar') }}
              </a>
            </td>
          </tr>
      @endforeach
    </tbody>
  </table>
</div>

aventon/resources/views/layouts/show_driver.blade.php
<div class="table-responsive">
  <table class="table table-hover">
    <tr>
      <td><strong>Nombre:</strong></td>
    </tr>
    <tr>
      <td>{!! $driver->name !!}</td>
    </tr>
    <tr>
      <td><strong>Apellido:</strong></td>
    </tr>
    <tr>
      <td>{!! $driver->lastname !!}</td>
    </tr>
    <tr>
      <td><strong>Calificación como conductor:</strong></td>
    </tr>
    <tr>
      <td>{!! $driver->driver_qualification !!}</td>
    </tr>
  </table>
</div>

aventon/resources/views/layouts/show_multiple_travel.blade.php
<div class="table-responsive">
  <table class="table table-hover">
    <tr>
      <td><strong>Fecha Salida:</strong></td>
      <td>{{ $travel->departure_date }}</td>
    </tr>
    <tr>
      <td><strong>Fecha Llegada:</strong></td>
      <td>{{ $travel->arrival_date }}</td>
    </tr>
    @foreach($multiple_travel as $multiple)
      <tr>
        <td><strong>Fecha Salida:</strong></td>
        <td>{{ $multiple->departure_date }}</td>
      </tr>
      <tr>
        <td><strong>Fecha Llegada:</strong></td>
        <td>{{ $multiple->arrival_date }}</td>
      </tr>
    @endforeach
    <tr>
      <td><strong>Hora Salida:</strong></td>
      <td>{{ $travel->departure_time }}</td>
    </tr>
    <tr>
      <td><strong>Hora Llegada:</strong></td>
      <td>{{ $travel->arrival_time }}</td>
    </tr>
    <tr>
      <td><strong>Costo:</strong></td>
      <td>{{ $travel->cost }}</td>
    </tr>
    <tr>
      <td><strong>Dirección Salida:</strong></td>
      <td>{{ $travel->departure_address}}</td>
    </tr>
    <tr>
      <td><strong>Dirección Llegada:</strong></td>
      <td>{{ $travel->arrival_address }}</td>
    </tr>
    <tr>
      <td><strong>Plazas  Disponibles:</strong></td>
      <td>{!! $travel->car->places !!}</td>
    </tr>
    <tr>
      <td><strong>Origen Provincia:</strong></td>
      <td>{{ $travel->source_province }}</td>
    </tr>
    <tr>
      <td><strong>Origen Localidad:</strong></td>
      <td>{{ $travel->source_locality}}</td>
    </tr>
    <tr>
      <td><strong>Destino Provincia:</strong>
      </td><td>{{ $travel->destiny_province }}</td>
    </tr>
    <tr>
      <td><strong>Destino Localidad:</strong>
      </td><td>{{ $travel->destiny_locality}}</td>
    </tr>
  </table>
</div>

aventon/resources/views/layouts/show_passenger.blade.php
<div class="table-responsive">
    <table class="table table-hover">
        <tbody> <!--aca tengo que hacer que este for recorra la tabla selection y por cada id de usuaior, buscar el usuario y mostrarlo-->
        <tr>
            <th><strong>Nombre:</strong></th>
            <th><strong>Apellido:</strong></th>
            <th><strong>Calificación como pasajero:</strong></th>
        </tr>
        <tr>
            <td>{!! $user->name !!}</td>
            <td>{!! $user->lastname !!}</td>
            <td>{!! $user->passenger_qualification !!}</td>
        </tr>
        </tbody>
    </table>
</div>

aventon/resources/views/layouts/show_postulants.blade.php
<div class="table-responsive">
    <table class="table table-hover">
        <tbody> <!--aca tengo que hacer que este for recorra la tabla selection y por cada id de usuaior, buscar el usuario y mostrarlo-->
        <tr>
            <th><strong>Nombre:</strong></th>
        </tr>
        @foreach( $travel->users as $postulant )
            @if ( $travel->user_id != $postulant->id )
            <tr>
                <td>{!! $postulant->name !!}</td>
                <td>
                    <a class="btn btn-primary" role="button" href="{{ route('travels.show_passenger', ['travel'=> $travel->id, 'user' => $postulant->id]) }}">
                        <img src="{{ asset('iconic-svg/check.svg') }}" alt="{{ __('Ver') }}">  {{ __('Ver') }}
                    </a>
                </td>
                <td>
                    <a class="btn btn-primary" role="button" href="{{ route('travels.accept_postulant', ['travel'=> $travel->id, 'user' => $postulant->id]) }}">
                        <img src="{{ asset('iconic-svg/check.svg') }}" alt="{{ __('Aceptar') }}">  {{ __('Aceptar') }}
                    </a>
                </td>
                <td>
                    <a class="btn btn-primary" role="button" href="{{ route('travels.reject_postulant', ['travel'=> $travel, 'user' => $postulant->id]) }}">
                        <img src="{{ asset('iconic-svg/x.svg') }}" alt="{{ __('Rechazar') }}">  {{ __('Rechazar') }}
                    </a>
                </td>
            </tr>
            @endif
        @endforeach
        </tbody>
    </table>
</div>

aventon/resources/views/layouts/show_selections.blade.php
<div class="table-responsive">
    <table class="table table-hover">
        <tbody> <!--aca tengo que hacer que este for recorra la tabla selection y por cada id de usuaior, buscar el usuario y mostrarlo-->
        <tr>
            <th><strong>Nombre:</strong></th>
        </tr>
        @foreach( $users as $user )
            <tr>
                <td>{!! $user->name !!}</td>
                <td>
                    <a class="btn btn-primary" role="button" href="{{ route('travels.show_passenger', ['travel'=> $travel->id, 'user' => $user->id]) }}">
                        <img src="{{ asset('iconic-svg/check.svg') }}" alt="{{ __('Ver') }}">  {{ __('Ver') }}
                    </a>
                </td>
                <td>
                    <a class="btn btn-primary" role="button" href="{{ route('travels.delete_passenger', ['travel'=> $travel, 'user' => $user->id]) }}">
                        <img src="{{ asset('iconic-svg/x.svg') }}" alt="{{ __('Eliminar') }}">  {{ __('Eliminar') }}
                    </a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

aventon/resources/views/layouts/show_travel.blade.php
<div class="table-responsive">
  <table class="table table-hover">
    <tr>
      <td><strong>Fecha Salida:</strong></td>
      <td>{{ $travel->departure_date }}</td>
    </tr>
    <tr>
      <td><strong>Hora Salida:</strong></td>
      <td>{{ $travel->departure_time }}</td>
    </tr>
    <tr>
      <td><strong>Costo:</strong></td>
      <td>{{ $travel->cost }}</td>
    </tr>
    <tr>
      <td><strong>Dirección Salida:</strong></td>
      <td>{{ $travel->departure_address}}</td>
    </tr>
    <tr>
      <td><strong>Dirección Llegada:</strong></td>
      <td>{{ $travel->arrival_address }}</td>
    </tr>
    <tr>
      <td><strong>Plazas  Disponibles:</strong></td>
      <td>{!! $travel->car->places !!}</td>
    </tr>
    <tr>
      <td><strong>Fecha Llegada:</strong></td>
      <td>{{ $travel->arrival_date }}</td>
    </tr>
    <tr>
      <td><strong>Hora Llegada:</strong></td>
      <td>{{ $travel->arrival_time }}</td>
    </tr>
    <tr>
      <td><strong>Origen Provincia:</strong></td>
      <td>{{ $travel->source_province }}</td>
    </tr>
    <tr>
      <td><strong>Origen Localidad:</strong></td>
      <td>{{ $travel->source_locality}}</td>
    </tr>
    <tr>
      <td><strong>Destino Provincia:</strong>
      </td><td>{{ $travel->destiny_province }}</td>
    </tr>
    <tr>
      <td><strong>Destino Localidad:</strong>
      </td><td>{{ $travel->destiny_locality}}</td>
    </tr>
  </table>
</div>

aventon/resources/views/layouts/show_user.blade.php
<div class="table-responsive">
  <table class="table table-hover">
    <tr>
      <td><strong>Nombre:</strong></td>
      <td>{!! Auth::user()->name !!}</td>
    </tr>
    <tr>
      <td><strong>Apellido:</strong></td>
      <td>{!! Auth::user()->lastname !!}</td>
    </tr>
    <tr>
      <td><strong>Correo electronico:</strong></td>
      <td>{!! Auth::user()->email !!}</td>
    </tr>
    <tr>
      <td><strong>Fecha de nacimiento:</strong></td>
      <td>{!! Auth::user()->birthdate !!}</td></tr>
    <tr>
      <td><strong>Calificación como conductor:</strong></td>
      <td>{!! Auth::user()->driver_qualification !!}</td>
    </tr>
    <tr>
      <td><strong>Calificación como pasajero:</strong></td>
      <td>{!! Auth::user()->passenger_qualification !!}</td>
    </tr>
    <tr>
      <td><strong>Cuenta:</strong></td>
      <td>{!! Auth::user()->account !!}</td>
    </tr>

  </table>
</div>