aventon/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * !! ACÁ SE PUEDE MODIFICAR TODAS LAS RUTAS - IMPORTANTE !!
 * Verbos en el protocolo HTTP: get, post, put.
 */

Route::get('/', function () {
    $travels = App\Travel::orderBy('departure_date','ASC')->where('multiple_id', '=', NULL)->where('arrival_date', '>=', date('Y-m-d H:i:s'))->paginate(7);
    return view('welcome', compact('travels'));
});

// AUTH

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')
        ->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')
        ->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')
        ->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')
        ->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')
        ->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')
        ->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/**
 * Rutas (cars, users, travels, questions, ratings) (Antes de los resources).
 */

// USERS
Route::pattern('users', '[0-9]+');
Route::get('/users/{user}/password', 'UserController@editPassword')
        ->name('users.edit_password');
Route::match(['put', 'patch'], '/users/{user}/password', 'UserController@updatePassword')
        ->name('users.update_password');
Route::get('/users/{user}/destroy', 'UserController@validateDestroy')
        ->name('users.validate_destroy');


// CARS
Route::pattern('cars', '[0-9]+');


// TRAVELS
Route::pattern('travels', '[0-9]+');
Route::get('/travels/{travel}/destroy', 'TravelController@validateDestroy')
        ->name('travels.validate_destroy');
Route::get('/travels/{travel}/selections', 'TravelController@showSelections')
        ->name('travels.show_selections');
Route::get('/travels/{travel}/passenger/{user}', 'TravelController@showPassenger')
        ->name('travels.show_passenger');
Route::get('/travels/search', 'TravelController@searchTravel')
    ->name('travels.search_travel');
Route::get('/travels/create_multiple', 'TravelController@createMultiple')
    ->name('travels.create_multiple');
Route::get('/travels/{travel}/edit_multiple', 'TravelController@editMultiple')
    ->name('travels.edit_multiple');
Route::match(['put', 'patch'], '/travels/{travel}/update_multiple', 'TravelController@updateMultiple')
    ->name('travels.update_multiple');
Route::post('/travels/store_multiple', 'TravelController@storeMultiple')
    ->name('travels.store_multiple');

// TRAVELS - POSTULANT
Route::get('/travels/{travel}/exit/{user}', 'TravelController@exitTravel')
        ->name('travels.exit_postulant');
Route::get('/travels/{travel}/exit_penal/{user}', 'TravelController@exitTravelWithPenal')
        ->name('travels.exit_postulant_penal');
Route::get('/travels/{travel}/delete/{user}', 'TravelController@deletePassenger')
        ->name('travels.delete_passenger');
Route::get('/travels/{travel}/postulants', 'TravelController@showPostulants')
        ->name('travels.show_postulants');
Route::get('/travels/{travel}/postulate', 'TravelController@postulate')
        ->name('travels.postulate');
Route::get('/travels/{travel}/reject/{user}', 'TravelController@rejectPostulant')
        ->name('travels.reject_postulant');
Route::get('/travels/{travel}/accept/{user}', 'TravelController@acceptPostulant')
        ->name('travels.accept_postulant');


// QUESTIONS
Route::pattern('questions', '[0-9]+');


// RATINGS
Route::pattern('ratings', '[0-9]+');
Route::get('/ratings/rate/{user}', 'RatingController@showRatings')
    ->name('ratings.show_ratings');


/**
 * Se genera CRUD's (index, store, create, destroy, update, show, edit).
 */

Route::resource('users','UserController');
Route::resource('cars','CarController');
Route::resource('travels','TravelController');
Route::resource('questions','QuestionController');
Route::resource('ratings','RatingController');

// HOME
Route::get('/home', 'HomeController@index')->name('home');

//CONTACTO
Route::get('/contact', 'ContactoController@contact')
        ->name('contact');

//AYUDA
Route::get('/ayuda', 'AyudaController@ayuda')
        ->name('ayuda');

aventon/app/Travel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Travel extends Model
{
    /**
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'car_id','user_id','departure_date','departure_time','cost',
        'departure_address','arrival_address','place_empty','arrival_date',
        'arrival_time','source_province','source_locality','destiny_province',
        'destiny_locality','multiple_id','multiple'
    ];

    public function users()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }
    
    public function car()
    {
        return $this->belongsTo(Car::class);
    }

    public function questions()
    {
      return $this->hasMany(Question::class);
    }
    public function ratings()
    {
        return $this->hasMany(Rating::class);
    }

    public function selections()
    {
        return $this->hasMany(Selection::class);
    }
}

aventon/app/Http/Controllers/TravelController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;
use App\Http\Requests\TravelRequest;
use Illuminate\Support\Facades\Auth;
use DateTime;
use Carbon\Carbon;

// APPS AVENTON
use App\Travel;
use App\Car;
use App\User;
use App\Selection;
use App\Rating;


class TravelController extends Controller
{
  /*
   * Funciones por defecto generadas por Route::resource en routes/web.php:
   * (index, store, create, destroy, update, show, edit).
   */

  public function index()
  {
    //
  }

  public function store(TravelRequest $request)
  {
    $user = Auth::user();
    $cost_travel = ($request->cost * 5) / 100;

    if( $user->account >= $cost_travel )
    {
      $departure_merge = new DateTime($request->departure_date .' ' .$request->departure_time);
      $arrival_merge = new DateTime($request->arrival_date .' ' .$request->arrival_time);

      // Valida que la partida sea menor que la de llegada.
      if( $arrival_merge < $departure_merge )
      {
        return back()
                ->with('info', 'Rango de fecha u hora incorrecto.')
                ->withInput();
      }
      else
      {
        // Valida que se encuentre en un rango de fecha disponible.
        $isInRange = $this->validateDate($departure_merge, $arrival_merge, $request->id);
        
        if( $isInRange )
        {
          $travel = new Travel;
          $car = Car::find($request->car_id); 

          $travel->car_id             = $car->id;
          $travel->user_id            = $user->id;
          $travel->departure_date     = $request->departure_date;
          $travel->arrival_date       = $request->arrival_date;
          $travel->departure_time     = $request->departure_time;
          $travel->arrival_time       = $request->arrival_time;
          $travel->cost               = $request->cost;
          $travel->departure_address  = $request->departure_address;
          $travel->arrival_address    = $request->arrival_address;
          $travel->place_empty        = $car->places;
          $travel->source_province    = $request->source_province;
          $travel->source_locality    = $request->source_locality;
          $travel->destiny_province   = $request->destiny_province;
          $travel->destiny_locality   = $request->destiny_locality;
          $travel->multiple           = $request->multiple;
          $travel->multiple_id        = $request->multiple_id;

          $travel->save();
          $user->travels()->save($travel);

          if($travel->multiple)
          {
              return back();
          }
          else
          {
              $user->decrement('account', $cost_travel);

              return redirect()
                  ->route('users.show', Auth::user())
                  ->with('info', 'El viaje ha sido creado');
          }
        }
        else
        {
          return back()
                  ->with('info', 'Hay un viaje en ese rango de fecha.')
                  ->withInput();
        }
      }
    }
    else
    {
      return back()
              ->with('info', 'No puedes dar de alta un viaje, porque tienes fondos insuficientes.')
              ->withInput();
    }
  }


  public function create()
  {
      $user   = Auth::user();
      $account_rating =0;
      foreach ($user->ratings as $rating)
      {
          if($rating->rate == 0 and $rating->date_for_rating < date("Y-m-d")) $account_rating++;
      }
      switch ($user) {
          case (count(Auth::user()->cars) == 0):
              return back()
                  ->with('info', 'No puedes dar de alta un viaje, no tenes autos');
              break;
          case ($user->account < 5):
              return back()
                  ->with('info', 'No puedes dar de alta un viaje, tienes fondos insuficientes.');
              break;
          case ($account_rating > 0 ):
              return back()
                  ->with('info', 'No puedes dar de alta un viaje, debes calificaciones ');
              break;
      }
      return view('travels.create');
  }


  // Primero se ejecuta validateDestroy.
  public function destroy($id)
  {
      $travel = Travel::find($id);
      $user   = Auth::user();



      // Elimina pasajeros y penaliza +1 por cada uno.
      if ( $travel->selections->count() != 0 )
      {
          foreach ($travel->selections as $selection )
          {
              $selection->delete();
              $user->decrement('driver_qualification');
          }
      }

      // Quita relación viaje-postulantes y penaliza +1.
      if ( $travel->users->count() > 1 )
      {
          foreach ($travel->users as $postulant )
          {
              $postulant->travels()->detach($travel->id);
          }

          $user->decrement('driver_qualification');
      }

      // Quita relación usuario-viaje.
      $user->travels()->detach($travel->id);

      // Elimina preguntas y respuestas.
      if ( $travel->questions->count() != 0 )
      {
          foreach ($travel->questions as $question )
          {
              $question->delete();
          }
      }

      // Elimina calificaciones teniendo encuenta ambos campos de user.
      if ( $travel->ratings->count() != 0 )
      {
          foreach ( Rating::all() as $rating )
          {
              if ( $rating->user_to_rating = $user->id or $rating->user_id = $user->id )
              {
                  $rating->delete();
              }
          }
      }

      $travel->delete();

      return redirect()
          ->route('users.show', Auth::user())
          ->with('info', 'El viaje a de la ciudad '.$travel->source_locality.' fue eliminado.');
  }


  public function update(TravelRequest $request, $id)
  {
    $travel = Travel::find($id);
    $hasPassangers = Selection::where('travel_id', $travel->id)->exists();
    $cantPostulants = $travel->users()->count();

    if ( $hasPassangers or $cantPostulants > 1)
    {
         return back()
              ->with('info', 'No puedes modificar el viaje, porque tienes pasajeros o postulantes en este viaje.');
    }
    else
    {
      $departure_merge = new DateTime($request->departure_date .' ' .$request->departure_time);
      $arrival_merge = new DateTime($request->arrival_date .' ' .$request->arrival_time);

      // Valida que la partida sea menor que la de llegada.
      if( $arrival_merge < $departure_merge )
      {
        return back()
                ->with('info', 'Rango de fecha u hora incorrecto.');
      }
      else
      {
        // Valida que se encuentre en un rango de fecha disponible.
        $isInRange = $this->validateDate($departure_merge, $arrival_merge, $id);
        
        if( $isInRange )
        {
          $car = Car::find($travel->car_id);

          $travel->departure_date     = $request->departure_date;
          $travel->arrival_date       = $request->arrival_date;
          $travel->departure_time     = $request->departure_time;
          $travel->arrival_time       = $request->arrival_time;
          $travel->cost               = $request->cost;
          $travel->departure_address  = $request->departure_address;
          $travel->arrival_address    = $request->arrival_address;
          $travel->place_empty        = $car->places;
          $travel->source_province    = $request->source_province;
          $travel->source_locality    = $request->source_locality;
          $travel->destiny_province   = $request->destiny_province;
          $travel->destiny_locality   = $request->destiny_locality;

          $travel->save();

          return redirect()
                  ->route('users.show', Auth::user())
                  ->with('info', 'El viaje con el auto de patente: ' . $travel->car->patent . ' ha sido actualizado');
        }
        else
        {
          return back()
                  ->with('info', 'Hay un viaje en ese rango de fecha.')
                  ->withInput();
        }
      }
    }
  }


  public function show($id)
  {
    $travel = Travel::find($id);

    if( $travel->multiple_id == NULL )
    {
      $is_driver = ( Auth::User()->id == $travel->user_id );

      if( !$is_driver )
      {
        $driver = User::find($travel->user_id);
      }

      $multiple_travel = Travel::where('multiple_id', '=', $id)->get();

      return view('travels.show', compact('travel', 'is_driver', 'driver', 'multiple_travel'));
    }
    else
    {
      return redirect()
              ->route('users.show', Auth::user())
              ->with('info', 'No tienes permitido acceder a ese viaje.');
    }
  }


  public function edit($id)
  {
    if( Auth::User()->travels()->where('travel_id', '=', $id)->exists() )
    {
      $travel = Travel::find($id);
      $is_editable = true;

      $hasPassangers = Selection::where('travel_id', $travel->id)->exists();
      $cantPostulants = $travel->users()->count();

      if ( $hasPassangers or $cantPostulants > 1)
      {
        return redirect()
                ->route('users.show', Auth::user())
                ->with('info', 'No puedes modificar el viaje, porque tienes pasajeros o postulantes en este viaje.');
      }

      return view('travels.edit', compact('travel', 'is_editable'));
    }
    else
    {
      return redirect()
              ->route('users.show', Auth::user())
              ->with('info', 'No tienes permitido acceder a ese viaje.');
    }
  }


  public function validateDestroy($id)
  {
    $travel = Travel::find($id);

    return view('travels.validate_destroy', compact('travel'));
  }


  public function showPostulants($id)
  {
    $travel = Travel::find($id);

    if( (Auth::User()->travels()->where('travel_id', '=', $id)->exists()) and ($travel->multiple_id == NULL) )
    {
      $multiple_travel = Travel::where('multiple_id', '=', $id)->get();

      return view('travels.show_postulants', compact('travel', 'multiple_travel'));
    }
    else
    {
      return redirect()
              ->route('users.show', Auth::user())

aventon/resources/views/travels/create.blade.php
@extends('layouts.app')

@section('content')
  @include('layouts.alerts')

  <div class="card col-md-5 mx-auto">
    <div class="card-header">
      <h5>
        {{ __('Agregar viaje') }}

        <a class="btn btn-primary float-right" role="button" href="{{ route('users.show', Auth::user()) }}">
          Volver
        </a>
      </h5>
    </div>

    <div class="card-body">
      <!-- Por defecto lo toma como POST -->
      {!! Form::open(['route' => 'travels.store']) !!}

        @include('travels.fragment.form_create')

      {!! Form::close() !!}
    </div>
  </div>
@endsection

aventon/resources/views/travels/create_multiple.blade.php
@extends('layouts.app')

@section('content')
  @include('layouts.alerts')

  <div class="card col-md-5 mx-auto">
    <div class="card-header">
      <h5>
        {{ __('Agregar viaje multiple') }}

        <a class="btn btn-primary float-right" role="button" href="{{ route('users.show', Auth::user()) }}">
          Volver
        </a>
      </h5>
    </div>

    <div class="card-body">
      <!-- Por defecto lo toma como POST -->
      {!! Form::open(['route' => 'travels.store_multiple']) !!}

        @include('travels.fragment.form_create_multiple')

      {!! Form::close() !!}
    </div>
  </div>
@endsection

aventon/resources/views/travels/edit.blade.php
@extends('layouts.app')

@section('content')
  @include('layouts.alerts')

  <div class="card col-md-5 mx-auto">
    <div class="card-header">
      <h5>
        {{ __('Viaje con el auto de patente: ').$travel->car->patent }}

        <a class="btn btn-primary float-right" role="button" href="{{ route('users.show', Auth::user()) }}">
          Volver
        </a>
      </h5>
    </div>

    <div class="card-body">
      {!! Form::model($travel, ['route' => ['travels.update', $travel], 'method' => 'PUT']) !!}

        @include('travels.fragment.form_edit')

      {!! Form::close() !!}
  </div>
@endsection

aventon/resources/views/travels/edit_multiple.blade.php
@extends('layouts.app')

@section('content')
  @include('layouts.alerts')

  <div class="card col-md-5 mx-auto">
    <div class="card-header">
      <h5>
        {{ __('Viaje con el auto de patente: ').$travel->car->patent }}

        <a class="btn btn-primary float-right" role="button" href="{{ route('users.show', Auth::user()) }}">
          Volver
        </a>
      </h5>
    </div>

    <div class="card-body">
      {!! Form::model($travel, ['route' => ['travels.update_multiple', $travel], 'method' => 'PUT']) !!}

        @include('travels.fragment.form_edit_multiple')

      {!! Form::close() !!}
  </div>
@endsection

aventon/resources/views/travels/search_travel.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.alerts')

    <div class="box-index card col-md-11 mx-auto">
        <div class="card-header">
            <h5>
                <a class="btn btn-primary float-right" role="button" href="{{ route('home') }}">
                    {{ __('Volver') }}
                </a>
            </h5>
        </div>

        <div class="card-body">
            @include('layouts.list_travels_home')
        </div>
    </div>
@endsection

aventon/resources/views/travels/show.blade.php
@extends('layouts.app')

@section('content')
  @include('layouts.alerts')
 
  <div class="row margenes-cajas">
    @if ( !$is_driver )
      <div class="card col-md-3 mx-auto">
        <div class="card-header">
          <h5>
            {{ __('Conductor del viaje: ').$driver->id }}
          </h5>
        </div>

        <div class="card-body">
          @include('layouts.show_driver')
        </div>
      </div>
    @endif

    <div class="card col-md-4 mx-auto">
      <div class="card-header">
        <h5>
          {{ __('Viaje con el auto de patente: ').$travel->car->patent }}
        </h5>
      </div>

      <div class="card-body">
        @if( $travel->multiple )
          @include('layouts.show_multiple_travel')
        @else
          @include('layouts.show_travel')
        @endif

        @if ( $is_driver )
          <div class="form-group">
            <a class="btn btn-primary btn-block" role="button" href="{{ route('travels.show_postulants', $travel) }}">
              <img src="{{ asset('iconic-svg/people.svg') }}" alt="{{ __('Postulantes') }}">  {{ __('Postulantes') }}
            </a>
          </div>
          <div class="form-group">
            <a class="btn btn-primary btn-block" role="button" href="{{ route('travels.show_selections', $travel) }}">
              <img src="{{ asset('iconic-svg/task.svg') }}" alt="{{ __('Seleccionados') }}">  {{ __('Seleccionados') }}
            </a>
          </div>
        @else
          <div class="form-group">
            <a class="btn btn-primary btn-block" role="button" href="{{ route('travels.postulate', $travel) }}">
              <img src="{{ asset('iconic-svg/plus.svg') }}" alt="{{ __('Postularme') }}">  {{ __('Postularme') }}
            </a>
          </div>
        @endif
      </div>
    </div>
    <div class="card col-md-4 mx-auto">
      @if ( $is_driver )
        <div class="card-header">
          <h5>
            {{ __('Preguntas :') }}
          </h5>
        </div>
        <div class="card-body">
            <p>
                @include('layouts.list_questions_drive')
            </p>
        </div>
      @else
        <div class="card-header">
          <h5>
            {{ __('Preguntar algo:') }}
          </h5>
        </div>
            <div class="card-body">
                <p>
                    @include('layouts.list_questions')
                </p>
            </div>
        @endif
    </div>
  </div>
@endsection

aventon/resources/views/travels/show_passenger.blade.php
@extends('layouts.app')

@section('content')
  @include('layouts.alerts')

  <div class="card col-md-4 mx-auto">
    <div class="card-header">
      <h5>
        {{ __('Usuario: ') }}

        <a class="btn btn-primary float-right" role="button" href="{{ route('travels.show', $travel) }}">
          {{ __('Volver') }}
        </a>
      </h5>
    </div>

    <div class="card-body">
      @include('layouts.show_passenger')
    </div>
  </div>
@endsection

aventon/resources/views/travels/show_postulants.blade.php
@extends('layouts.app')

@section('content')
  @include('layouts.alerts')

  <div class="card col-md-4 mx-auto">
    <div class="card-header">
      <h5>
        {{ __('Viaje con el auto de patente: ').$travel->car->patent }}

        <a class="btn btn-primary float-right" role="button" href="{{ route('travels.show', $travel) }}">
          {{ __('Volver') }}
        </a>
      </h5>
    </div>

    <div class="card-body">
      @include('layouts.show_postulants')
    </div>
  </div>
@endsection

aventon/resources/views/travels/show_selections.blade.php
@extends('layouts.app')

@section('content')
  @include('layouts.alerts')

  <div class="card col-md-4 mx-auto">
    <div class="card-header">
      <h5>
        {{ __('Viaje con el auto de patente: ').$travel->car->patent }}

        <a class="btn btn-primary float-right" role="button" href="{{ route('travels.show', $travel) }}">
          {{ __('Volver') }}
        </a>
      </h5>
    </div>

    <div class="card-body">
      @include('layouts.show_selections')
    </div>
  </div>
@endsection

aventon/resources/views/travels/validate_destroy.blade.php
@extends('layouts.app')

@section('content')
  @include('layouts.alerts')

  <div class="card col-md-5 mx-auto">
    <div class="card-header">
      <h5>
        {{ __('Eliminar viaje a' ) }}{{ $travel->source_locality }}

        <a class="btn btn-primary float-right" role="button" href="{{ route('users.show', Auth::user()) }}">
          {{ __('Volver') }}
        </a>
      </h5>
    </div>

    <div class="card-body">
      <h2>
        <p>{{ __('¿Estas seguro que quieres eliminar el viaje?') }}</p>
      </h2>
      <h5>
      <p>{{ __('Ten en cuenta que si eliminas el viaje tu calificacion como conductor será penalizada') }}</p>
      <h5>
      <div class="form-group">
        <form action="{{ route('travels.destroy', $travel->id) }}" method="post">
          {{ csrf_field() }}
          <input type="hidden" name="_method" value="DELETE">
          <button class="btn btn-primary float-right">
            <img src="{{ asset('iconic-svg/warning.svg') }}" alt="{{ __('Eliminar Viaje') }}">  {{ __('Eliminar Viaje') }}
          </button>
        </form>
      </div>
    </div>
  </div>
@endsection